"""Python backend kit for the Mutsuki Rust-first runtime."""

from mutsuki_runtime_python.backend import (
    BackendInvokeError,
    OperationBackend,
    ResourceBackend,
    StrategyBackend,
)
from mutsuki_runtime_python.contracts import (
    ERR_AGENT_NOT_FOUND,
    ERR_CAPABILITY_EXHAUSTED,
    ERR_OPERATION_NOT_FOUND,
    ERR_REF_NOT_FOUND,
    ERR_RUNTIME_BACKEND_FAILED,
    ERR_RUNTIME_BACKEND_GENERATION_MISMATCH,
    ERR_SCOPE_NO_MATCH,
    ERR_SOURCE_UNREGISTERED,
    AgentParticipation,
    AgentPhase,
    AgentSpec,
    Envelope,
    LeaseToken,
    OperationDescriptor,
    OperationHandlerKey,
    OperationSnapshot,
    OperationStatus,
    RefDescriptor,
    ResourceRecord,
    RuntimeError,
    RuntimeEvent,
    RuntimeEventKind,
    ScopeRuleSpec,
    SideEffectPolicy,
    SourceDescriptor,
    SourceRef,
    SourceSnapshot,
    SpanStatus,
    StrategyResult,
    StrategyResultStatus,
    TraceSpan,
    from_json_bytes,
    from_json_dict,
    to_json_bytes,
    to_json_dict,
)
from mutsuki_runtime_python.host import PythonBackendHost
from mutsuki_runtime_python.resource import IdSource, PythonResourceBackend
from mutsuki_runtime_python.stdio import StdioJsonlBackendServer, run_stdio_server

__all__ = [
    "ERR_AGENT_NOT_FOUND",
    "ERR_CAPABILITY_EXHAUSTED",
    "ERR_OPERATION_NOT_FOUND",
    "ERR_REF_NOT_FOUND",
    "ERR_RUNTIME_BACKEND_FAILED",
    "ERR_RUNTIME_BACKEND_GENERATION_MISMATCH",
    "ERR_SCOPE_NO_MATCH",
    "ERR_SOURCE_UNREGISTERED",
    "AgentParticipation",
    "AgentPhase",
    "AgentSpec",
    "BackendInvokeError",
    "Envelope",
    "IdSource",
    "LeaseToken",
    "OperationBackend",
    "OperationDescriptor",
    "OperationHandlerKey",
    "OperationSnapshot",
    "OperationStatus",
    "PythonBackendHost",
    "PythonResourceBackend",
    "RefDescriptor",
    "ResourceBackend",
    "ResourceRecord",
    "RuntimeError",
    "RuntimeEvent",
    "RuntimeEventKind",
    "ScopeRuleSpec",
    "SideEffectPolicy",
    "SourceDescriptor",
    "SourceRef",
    "SourceSnapshot",
    "SpanStatus",
    "StdioJsonlBackendServer",
    "StrategyBackend",
    "StrategyResult",
    "StrategyResultStatus",
    "TraceSpan",
    "from_json_bytes",
    "from_json_dict",
    "run_stdio_server",
    "to_json_bytes",
    "to_json_dict",
]
